Update psalm.yml

diff --git a/.github/workflows/psalm.yml b/.github/workflows/psalm.yml
--- a/.github/workflows/psalm.yml
+++ b/.github/workflows/psalm.yml
@@ -23,11 +23,13 @@ jobs:
       - name: Set up PHP with GD extension
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '8.3' # Specify the PHP version you need
-          extensions: gd # Install GD extension
+          php-version: '8.3'
+          extensions: gd
 
       - name: Verify GD Extension
-        run: php -m | grep gd # Check if GD extension is loaded
+        run: |
+          php -m | grep gd || echo "GD extension not found"
+          php -r "extension_loaded('gd') ? exit(0) : exit(1);"
 
       - name: Install Composer Dependencies
         run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-req=ext-gd
